# docker-compose.yml: docker-compose configuration file "Hermes" capstone project

networks:
  app-network:
    driver: bridge
volumes:
  mysql-data:

services:
  gui:
    build:
      context: ./gui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network

  web-scanner:
    build:
      context: ./web-scanner
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  server:
    build:
      context: ./weak-website/server
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    volumes:
      - ./server/src:/usr/src/app/src
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - SWAGGER_ENABLED=${SWAGGER_ENABLED}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_PROTOCOL=${PROTOCOL}
      - SERVER_HOST=${HOST}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - app-network

  client:
    build:
      context: ./weak-website/client
      dockerfile: Dockerfile.prod
    environment:
      - VITE_CLIENT_PORT=${CLIENT_PORT}
      - VITE_SERVER_URL=${SERVER_URL}
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network
